args_parser.h File Reference
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include quad_solver.h
Classes
struct ArgsTest
Specifies test mode parameters.
struct Argument
Specifies console argument parametres: name, function and description.
Enumerations
enum class ArgsMode { ERROR = -1
, EXIT = 0
, CONTINUE = 1
 }
Specifies int main() returns.
Functions
ArgsMode print_help (const Argument args_dict[], const int args_dict_len, int *arg_i, int argc, char *argv[], ArgsTest *args_test)
Prints help.
ArgsMode read_test_filename (const Argument args_dict[], const int args_dict_len, int *arg_i, int argc, char *argv[], ArgsTest *args_test)
Reads test file name from console.
Status::Statuses args_parse (int argc, char *argv[], ArgsTest *test)
Parses console arguments.
void enable_test_args (Argument args_dict[], const int args_dict_len)
Enables test mode args in args_dict.
Enumeration Type Documentation
ArgsMode
enum class ArgsMode [strong]
Specifies int main() returns.
Enumerator
ERROR Error.
EXIT Continue reading args, but then normal exit.
CONTINUE Continue reading args.
Definition at line 13 of file args_parser.h.
                    {
    ERROR = -1,
    EXIT = 0,
    CONTINUE = 1,
};
Function Documentation
args_parse()
Status::Statuses args_parse (int argc, char * argv[], ArgsTest * test)
Parses console arguments.
Parameters
 in argc
 in argv
 out filename for test mode
Returns
Status::Statuses
< args_dict array len
This array contains console options, their functions and descriptions
< Help option
Definition at line 3 of file args_parser.cpp.
                                                                       {
    assert(argv);
    assert(argc);
    assert(args_test);
    assert(args_test->filename == nullptr);
    static const int ARGS_DICT_LEN = 2;
    static Argument args_dict[ARGS_DICT_LEN] = {
        {"-h", print_help, "# -h - prints help information\n", true},
        {"-t", read_test_filename, "# -t - specify test file name after this (works only if test mode enabled)\n"
                                    "# Test file format (there might be several such sections):\n"
                                    "# <coeff a> <coeff b> <coeff c>\n"
                                    "# <solutions number>\n"
                                    "# <solution 1 (if exists)> <solution 2 (if exists)>\n"
                                    "# \n"
                                    "# <Next test>\n", false}
    };
    if(args_test->is_enabled)
        enable_test_args(args_dict, ARGS_DICT_LEN);
    bool exit = false;
    for (int i = 1; i < argc; i++) {
        bool is_found = false;
        for (int j = 0; j < ARGS_DICT_LEN; j++) {
            if (args_dict[j].is_enabled && strcmp(argv[i], args_dict[j].arg) == 0) {
                switch (args_dict[j].func(args_dict, ARGS_DICT_LEN, &i, argc, argv, args_test)) {
                    case ArgsMode::CONTINUE:
                        break;
                    case ArgsMode::EXIT:
                        exit = true;
                        break;
                    case ArgsMode::ERROR:
                        return Status::ARGS;
                    default:
                        assert(0 && "args[j].func() returned wrong ArgsMode");
                        break;
                }
                is_found = true;
                break;
            }
        }
        if (is_found)
            continue;
        printf("Wrong console argument: %s\n"
               "Use -h for help\n", argv[i]);
        return Status::ARGS;
    }
    if (exit)
        return Status::OK_EXIT;
    return Status::NORMAL_WORK;
}
References Status::ARGS, CONTINUE, enable_test_args(), ERROR, EXIT, ArgsTest::filename, ArgsTest::is_enabled, Status::NORMAL_WORK, Status::OK_EXIT, print_help(), and read_test_filename().
Referenced by main().
enable_test_args()
void enable_test_args (Argument args_dict[], const int args_dict_len) [inline]
Enables test mode args in args_dict.
Parameters
 out args_dict
 in args_dict_len
Definition at line 83 of file args_parser.h.
                                                                            {
    assert(args_dict);
    for (int i = 0; i < args_dict_len; i++) {
        if (strcmp(args_dict[i].arg, "-t") == 0)
            args_dict[i].is_enabled = true;
    }
}
References Argument::is_enabled.
Referenced by args_parse().
print_help()
ArgsMode print_help (const Argument args_dict[], const int args_dict_len, int * arg_i, int argc, char * argv[], ArgsTest * args_test)
Prints help.
Parameters
 in args_dict
 in args_dict_len
 in arg_i number of current argument
 in argc int main() argc
 in argv int main() argv
 in args_test
Returns
ArgsMode
Definition at line 64 of file args_parser.cpp.
                                                                                   {
    assert(args_list);
    assert(args_list_len >= 0);
    assert(arg_i);
    assert(argc);
    assert(argv);
    assert(args_test);
    printf("# This program solves quad equations of the form a*x^2 + b*x + c = 0\n"
           "# Where \"x\" is a variable and \"a\", \"b\", \"c\" are coefficients\n"
           "# Console args:\n");
    for (int i = 0; i < args_list_len; i++) {
        if (!args_list[i].is_enabled)
            continue;
        printf("%s", args_list[i].description);
    }
    printf("# End of help. Good luck using this program!\n");
    return ArgsMode::EXIT;
}
References EXIT.
Referenced by args_parse().
read_test_filename()
ArgsMode read_test_filename (const Argument args_dict[], const int args_dict_len, int * arg_i, int argc, char * argv[], ArgsTest * args_test)
Reads test file name from console.
Parameters
 in args_dict
 in args_dict_len
 in arg_i number of current argument
 in argc int main() argc
 in argv int main() argv
 out args_test
Returns
ArgsMode
Definition at line 88 of file args_parser.cpp.
                                                                                     {
    assert(args_list);
    assert(args_list_len >= 0);
    assert(arg_i);
    assert(argv);
    assert(args_test);
    if (++(*arg_i) >= argc) {
        printf("No test file name found\n");
        return ArgsMode::ERROR;
    }
    args_test->filename = argv[*arg_i];
    return ArgsMode::CONTINUE;
}
References CONTINUE, ERROR, and ArgsTest::filename.
Referenced by args_parse().