input.h File Reference
#include <stdio.h>
#include <ctype.h>
#include <math.h>
#include <assert.h>
Enumerations
enum class InputStatus { END_OF_FILE = -1
, WRONG_DATA = 0
, OK = 1
 }
Specifies input errors.
Functions
InputStatus read_num (double *x, FILE *stream=stdin, bool flush=true)
Reads double from input to pointer.
InputStatus read_num (int *x, FILE *stream=stdin, bool flush=true)
Reads int from input to pointer.
bool input_flush (FILE *stream=stdin)
Flushes input.
Enumeration Type Documentation
InputStatus
enum class InputStatus [strong]
Specifies input errors.
Enumerator
END_OF_FILE End of file reached.
WRONG_DATA Input error.
OK OK.
Definition at line 12 of file input.h.
                       {
    END_OF_FILE = -1,
    WRONG_DATA = 0,
    OK = 1
};
Function Documentation
input_flush()
bool input_flush (FILE * stream = stdin)
Flushes input.
Parameters
 in stream
Returns
bool false - if there are non space symbols in stream left
Definition at line 31 of file input.cpp.
                               {
    assert(stream);
    int c = ' ';
    bool non_space = true;
    do {
        if (!isspace(c))
            non_space = false;
    } while ((c = fgetc(stream)) != '\n' && c != EOF && !feof(stream) && !ferror(stream));
    return non_space;
}
Referenced by read_num(), read_num(), test_enter_coeffs(), and test_read_roots().
read_num() [1/2]
InputStatus read_num (double * x, FILE * stream = stdin, bool flush = true)
Reads double from input to pointer.
Parameters
 in x
 in stream
 in flush enables input_flush() at the end
Returns
int success
Definition at line 3 of file input.cpp.
                                                          {
    assert(x);
    assert(stream);
    int res = fscanf(stream, "%lf", x);
    if (res == EOF)
        return InputStatus::END_OF_FILE;
    else if (res == 1 && isfinite(*x) && (!flush || input_flush(stream))) {
        return InputStatus::OK;
    } else {
        return InputStatus::WRONG_DATA;
    }
}
References END_OF_FILE, input_flush(), OK, and WRONG_DATA.
Referenced by test_enter_coeffs(), and test_read_roots().
read_num() [2/2]
InputStatus read_num (int * x, FILE * stream = stdin, bool flush = true)
Reads int from input to pointer.
Parameters
 in x
 in stream
 in flush enables input_flush() at the end
Returns
int success
Definition at line 17 of file input.cpp.
                                                       {
    assert(x);
    assert(stream);
    int res = fscanf(stream, "%d", x);
    if (res == EOF)
        return InputStatus::END_OF_FILE;
    else if (res == 1 && (!flush || input_flush(stream))) {
        return InputStatus::OK;
    } else {
        return InputStatus::WRONG_DATA;
    }
}
References END_OF_FILE, input_flush(), OK, and WRONG_DATA.