input.cpp File Reference
#include input.h
Functions
InputStatus read_num (double *x, FILE *stream, bool flush)
Reads double from input to pointer.
InputStatus read_num (int *x, FILE *stream, bool flush)
Reads int from input to pointer.
bool input_flush (FILE *stream)
Flushes input.
Function Documentation
input_flush()
bool input_flush (FILE * stream = stdin)
Flushes input.
Parameters
 in stream
Returns
bool false - if there are non space symbols in stream left
Definition at line 31 of file input.cpp.
                               {
    assert(stream);
    int c = ' ';
    bool non_space = true;
    do {
        if (!isspace(c))
            non_space = false;
    } while ((c = fgetc(stream)) != '\n' && c != EOF && !feof(stream) && !ferror(stream));
    return non_space;
}
Referenced by read_num(), read_num(), test_enter_coeffs(), and test_read_roots().
read_num() [1/2]
InputStatus read_num (double * x, FILE * stream = stdin, bool flush = true)
Reads double from input to pointer.
Parameters
 in x
 in stream
 in flush enables input_flush() at the end
Returns
int success
Definition at line 3 of file input.cpp.
                                                          {
    assert(x);
    assert(stream);
    int res = fscanf(stream, "%lf", x);
    if (res == EOF)
        return InputStatus::END_OF_FILE;
    else if (res == 1 && isfinite(*x) && (!flush || input_flush(stream))) {
        return InputStatus::OK;
    } else {
        return InputStatus::WRONG_DATA;
    }
}
References END_OF_FILE, input_flush(), OK, and WRONG_DATA.
Referenced by test_enter_coeffs(), and test_read_roots().
read_num() [2/2]
InputStatus read_num (int * x, FILE * stream = stdin, bool flush = true)
Reads int from input to pointer.
Parameters
 in x
 in stream
 in flush enables input_flush() at the end
Returns
int success
Definition at line 17 of file input.cpp.
                                                       {
    assert(x);
    assert(stream);
    int res = fscanf(stream, "%d", x);
    if (res == EOF)
        return InputStatus::END_OF_FILE;
    else if (res == 1 && (!flush || input_flush(stream))) {
        return InputStatus::OK;
    } else {
        return InputStatus::WRONG_DATA;
    }
}
References END_OF_FILE, input_flush(), OK, and WRONG_DATA.