quad_solver.h File Reference
#include <stdio.h>
#include <ctype.h>
#include <math.h>
#include <assert.h>
#include input.h
Classes
struct Status
Specifies functions status.
struct EqSolverData
Contains input and output data for solver.
Enumerations
enum Solutions {
NAN_SOLUTIONS = -2
, INFINITE_SOLUTIONS = -1
, NO_SOLUTIONS = 0
, ONE_SOLUTION = 1
,
TWO_SOLUTIONS = 2
 }
Specifies number of soludions of the equation.
Functions
void EqSolverData_init (EqSolverData *data)
Inits EqSolverData struct.
Status::Statuses solver_proccess ()
Main proccess (read, solve and print)
InputStatus enter_coeffs (EqSolverData *data)
Reads coefficients from input to data->coeffs, starting with name 'a'.
void solve_lin (EqSolverData *data)
Solves linear equations.
void solve_quad (EqSolverData *data)
Solves quad equations.
void print_roots (const EqSolverData *data)
Prints roots.
bool is_double_equal (const double a, const double b)
Tells if two doubles are equal with precision of DOUBLE_COMPARE_PRECISION.
double valid_root (double root)
Returns valid root (check for -0.0)
void swap (double *a, double *b)
Swaps values of two pointers.
void bubble_sort (double *arr, int size)
Bubble sorting algorithm.
Enumeration Type Documentation
Solutions
enum Solutions
Specifies number of soludions of the equation.
Enumerator
NAN_SOLUTIONS Poison value.
INFINITE_SOLUTIONS Infinite number of solutions.
NO_SOLUTIONS 0 solutions
ONE_SOLUTION 1 solutions
TWO_SOLUTIONS 2 solutions
Definition at line 37 of file quad_solver.h.
               {
    NAN_SOLUTIONS = -2,
    INFINITE_SOLUTIONS = -1,
    NO_SOLUTIONS = 0,
    ONE_SOLUTION = 1,
    TWO_SOLUTIONS = 2
};
Function Documentation
bubble_sort()
void bubble_sort (double * arr, int size) [inline]
Bubble sorting algorithm.
Parameters
arr array
size array size
Definition at line 152 of file quad_solver.h.
                                               {
    for (int i = 0; i < size - 1; i++)
        for (int j = 0; j < size - 1; j++)
            if (arr[j] > arr[j+1])
                swap(arr + j, arr + j + 1);
}
References swap().
Referenced by solve_quad(), and test_read_roots().
enter_coeffs()
InputStatus enter_coeffs (EqSolverData * data)
Reads coefficients from input to data->coeffs, starting with name 'a'.
Parameters
 in data
Returns
InputStatus
Definition at line 62 of file quad_solver.cpp.
                                             {
    assert(data);
    for (int i = 0; i < EqSolverData::COEFF_NUM; i++) {
        InputStatus res = enter_coeff('a' + (char)i, data->coeffs + i);
        if (res != InputStatus::OK)
            return res;
    }
    return InputStatus::OK;
}
References EqSolverData::COEFF_NUM, EqSolverData::coeffs, and OK.
Referenced by solver_proccess().
EqSolverData_init()
void EqSolverData_init (EqSolverData * data) [inline]
Inits EqSolverData struct.
Parameters
 in data pointer
Definition at line 61 of file quad_solver.h.
                                                  {
    data->roots_num = NAN_SOLUTIONS;
    for (int i = 0; i < EqSolverData::COEFF_NUM; i++)
        data->coeffs[i] = NAN;
    for (int i = 0; i < EqSolverData::COEFF_NUM - 1; i++)
        data->roots[i] = NAN;
}
References EqSolverData::COEFF_NUM, EqSolverData::coeffs, NAN_SOLUTIONS, EqSolverData::roots, and EqSolverData::roots_num.
Referenced by solver_proccess(), and test_proccess().
is_double_equal()
bool is_double_equal (const double a, const double b) [inline]
Tells if two doubles are equal with precision of DOUBLE_COMPARE_PRECISION.
Parameters
 in a First double
 in b Second double
Returns
bool (a == b)
Definition at line 112 of file quad_solver.h.
                                                            {
    assert(!isnan(a) && !isinf(a) && !isnan(b) && !isinf(b));
    static const double DOUBLE_COMPARE_PREC = 0.000001;
    return fabs(a - b) < DOUBLE_COMPARE_PREC;
};
Referenced by solve_lin(), solve_quad(), test_compare_data(), and valid_root().
print_roots()
void print_roots (const EqSolverData * data)
Prints roots.
Parameters
 in data
Definition at line 124 of file quad_solver.cpp.
                                          {
    assert(data);
    switch (data->roots_num) {
        case NO_SOLUTIONS:
            printf("No solutions\n");
            break;
        case ONE_SOLUTION:
            assert(isfinite(data->roots[0]));
            printf("1 solution:\nx = %lf\n", data->roots[0]);
            break;
        case TWO_SOLUTIONS:
            assert(isfinite(data->roots[0]) && isfinite(data->roots[1]));
            printf("2 solutions:\nx1 = %lf\nx2 = %lf\n", data->roots[0], data->roots[1]);
            break;
        case INFINITE_SOLUTIONS:
            printf("Infinite number of solutions:\nx belongs to the set (-inf; +inf)\n");
            break;
        case NAN_SOLUTIONS:
        default:
            assert(0 && "Incorrect solutions number");
            break;
    }
}
References INFINITE_SOLUTIONS, NAN_SOLUTIONS, NO_SOLUTIONS, ONE_SOLUTION, EqSolverData::roots, EqSolverData::roots_num, and TWO_SOLUTIONS.
Referenced by solver_proccess().
solve_lin()
void solve_lin (EqSolverData * data)
Solves linear equations.
Parameters
 in data
Definition at line 108 of file quad_solver.cpp.
                                   {
    assert(data);
    assert(EqSolverData::COEFF_NUM >= 2);
    double a = data->coeffs[EqSolverData::COEFF_NUM - 2];
    double b = data->coeffs[EqSolverData::COEFF_NUM - 1];
    if (is_double_equal(a, 0)) {
        data->roots_num = is_double_equal(b, 0) ? INFINITE_SOLUTIONS : NO_SOLUTIONS;
        return;
    }
    data->roots[0] = valid_root(b / -a);
    data->roots_num = ONE_SOLUTION;
}
References EqSolverData::COEFF_NUM, EqSolverData::coeffs, INFINITE_SOLUTIONS, is_double_equal(), NO_SOLUTIONS, ONE_SOLUTION, EqSolverData::roots, EqSolverData::roots_num, and valid_root().
Referenced by solve_quad().
solve_quad()
void solve_quad (EqSolverData * data)
Solves quad equations.
Parameters
 in data
Definition at line 73 of file quad_solver.cpp.
                                   {
    assert(data);
    assert(EqSolverData::COEFF_NUM >= 3);
    double a = data->coeffs[EqSolverData::COEFF_NUM - 3];
    double b = data->coeffs[EqSolverData::COEFF_NUM - 2];
    double c = data->coeffs[EqSolverData::COEFF_NUM - 1];
    if (is_double_equal(a, 0)) { // check if equation is quad (zero division check)
        solve_lin(data);
        return;
    }
    double D = b*b - 4*a*c; // discriminant
    if (is_double_equal(D, 0)) { // check if there are solutions
        data->roots[0] = valid_root((-b) / (2*a));
        data->roots_num = ONE_SOLUTION;
    } else if (D < 0) {
        data->roots_num = NO_SOLUTIONS;
    } else {
        double D_sqrt = NAN;
        if (is_double_equal(c, 0))
            D_sqrt = b;
        else
            D_sqrt = sqrt(D);
        assert(isfinite(D_sqrt));
        double double_a = a * 2;
        data->roots[0] = valid_root((-b - D_sqrt) / double_a);
        data->roots[1] = valid_root((-b + D_sqrt) / double_a);
        data->roots_num = TWO_SOLUTIONS;
    }
    bubble_sort(data->roots, data->roots_num);
}
References bubble_sort(), EqSolverData::COEFF_NUM, EqSolverData::coeffs, is_double_equal(), NO_SOLUTIONS, ONE_SOLUTION, EqSolverData::roots, EqSolverData::roots_num, solve_lin(), TWO_SOLUTIONS, and valid_root().
Referenced by solver_proccess(), and test_proccess().
solver_proccess()
Status::Statuses solver_proccess ()
Main proccess (read, solve and print)
Returns
Status::Statuses
Definition at line 13 of file quad_solver.cpp.
                                 {
    EqSolverData data = {};
    EqSolverData_init(&data);
    switch (enter_coeffs(&data)) {
        case InputStatus::OK:
            break;
        case InputStatus::WRONG_DATA:
            return Status::COEFFS_INPUT;
        case InputStatus::END_OF_FILE:
            return Status::END_OF_FILE;
        default:
            assert(0 && "enter_coeffs() returned wrong InputStatus");
            break;
    }
    for (int i = 0; i < EqSolverData::COEFF_NUM; i++)
        assert(isfinite(data.coeffs[i]));
    solve_quad(&data);
    print_roots(&data);
    return Status::NO_ERROR;
}
References EqSolverData::COEFF_NUM, EqSolverData::coeffs, Status::COEFFS_INPUT, END_OF_FILE, Status::END_OF_FILE, enter_coeffs(), EqSolverData_init(), Status::NO_ERROR, OK, print_roots(), solve_quad(), and WRONG_DATA.
Referenced by main(), and test_or_normal().
swap()
void swap (double * a, double * b) [inline]
Swaps values of two pointers.
Parameters
a First pointer
b Second pointer
Definition at line 137 of file quad_solver.h.
                                       {
    // --------------
    // | |
    double c = *a; // |
               *a = *b;//v
                    *b = c;
}
Referenced by bubble_sort().
valid_root()
double valid_root (double root) [inline]
Returns valid root (check for -0.0)
Parameters
root
Returns
double
Definition at line 125 of file quad_solver.h.
                                      {
    if (is_double_equal(root, 0))
        return fabs(root);
    return root;
}
References is_double_equal().
Referenced by solve_lin(), and solve_quad().