test/test.h File Reference
#include <assert.h>
#include ../quad_solver.h
#include ../args_parser.h
#include ../console.h
Enumerations
enum class TestMode { INPUT_ERROR = -1
, NO_TESTS = 0
, TESTS_LEFT = 1
 }
Specifies test modes.
enum class TestResult { ERROR = -1
, FAILED = 0
, PASSED = 1
 }
Specifies test results.
Functions
TestMode test_open_file (FILE **file, const char *filename)
Opens test file by filename.
TestMode test_enter_coeffs (EqSolverData *data, FILE *file)
Reads coeffs from test file.
Status::Statuses test_or_normal (const char *filename)
Opens test file and decides: solver_proccess() or test_proccess()
Status::Statuses test_proccess (FILE *file)
Main test proccess (read, test)
bool test_read_roots (const EqSolverData *data, EqSolverData *correct_data, FILE *file)
Reads correct roots from test file.
TestResult test_compare_data (const EqSolverData *data, const EqSolverData *correct_data, const int test_n)
Compares solutinons number and roots.
TestResult test_read_and_compare (const EqSolverData *data, FILE *file, const int test_n)
calls test_read_roots and test_compare_data
void test_print_summary (const int test_num, const int passed_test_num)
Prints summary about all tests.
Enumeration Type Documentation
TestMode
enum class TestMode [strong]
Specifies test modes.
Enumerator
INPUT_ERROR Input error.
NO_TESTS No tests left in file or user didn't dpecified test mode.
TESTS_LEFT There are tests left in the file.
Definition at line 13 of file test.h.
                    {
    INPUT_ERROR = -1,
    NO_TESTS = 0,
    TESTS_LEFT = 1
};
TestResult
enum class TestResult [strong]
Specifies test results.
Enumerator
ERROR
FAILED
PASSED
Definition at line 67 of file test.h.
                      {
    ERROR = -1,
    FAILED = 0,
    PASSED = 1
};
Function Documentation
test_compare_data()
TestResult test_compare_data (const EqSolverData * data, const EqSolverData * correct_data, const int test_n)
Compares solutinons number and roots.
Parameters
 in data
 in correct_data
 in test_n number of test
Definition at line 129 of file test.cpp.
                                                                                                           {
    assert(data);
    assert(correct_data);
    printf("Test %d. ", test_n);
    if (data->roots_num != correct_data->roots_num) {
        printf("Incorrect number of solutions.\n"
               CONSOLE_RED("Test %d FAILED!\n"), test_n);
        return TestResult::FAILED;
    }
    bool passed = true;
    for (int i = 0; i < (int) correct_data->roots_num; i++) {
        assert(isfinite(data->roots[i]) && isfinite(correct_data->roots[i]));
        if (!is_double_equal(data->roots[i], correct_data->roots[i])) {
            printf("Incorrect root %d\n", (i+1));
            printf(" Correct root: %lf\n", correct_data->roots[i]);
            printf(" Received root: %lf\n", data->roots[i]);
            passed = false;
        }
    }
    if (!passed) {
        printf(CONSOLE_RED("Test %d FAILED!\n"), test_n);
        return TestResult::FAILED;
    }
    printf("Passed\n");
    return TestResult::PASSED;
}
References CONSOLE_RED, FAILED, is_double_equal(), PASSED, EqSolverData::roots, and EqSolverData::roots_num.
Referenced by test_read_and_compare().
test_enter_coeffs()
TestMode test_enter_coeffs (EqSolverData * data, FILE * file)
Reads coeffs from test file.
Parameters
 in data
 in file
Returns
TestMode
Definition at line 77 of file test.cpp.
                                                           {
    assert(data);
    assert(file);
    for (int i = 0; i < EqSolverData::COEFF_NUM; i++) {
        switch (read_num(data->coeffs + i, file, false)) {
            case InputStatus::END_OF_FILE:
                return TestMode::NO_TESTS;
            case InputStatus::WRONG_DATA:
                printf("Error reading coefficient from test file\n");
                return TestMode::INPUT_ERROR;
            case InputStatus::OK:
                break;
            default:
                assert(0 && "read_num() returned wrong InputStatus");
                break;
        }
    }
    if (!input_flush(file)) {
        printf("Error reading coefficient from test file\n");
        return TestMode::INPUT_ERROR;
    }
    return TestMode::TESTS_LEFT;
}
References EqSolverData::COEFF_NUM, EqSolverData::coeffs, END_OF_FILE, INPUT_ERROR, input_flush(), NO_TESTS, OK, read_num(), TESTS_LEFT, and WRONG_DATA.
Referenced by test_proccess().
test_open_file()
TestMode test_open_file (FILE ** file, const char * filename)
Opens test file by filename.
Parameters
 out file - pointer
 in filename - name of file
Returns
TestMode
Definition at line 61 of file test.cpp.
                                                           {
    assert(file);
    if (filename == nullptr)
        return TestMode::NO_TESTS;
    *file = fopen(filename, "r");
    if (*file == nullptr) {
        printf("Error opening test file %s\n", filename);
        perror("Message");
        fclose(*file);
        return TestMode::INPUT_ERROR;
    }
    return TestMode::TESTS_LEFT;
}
References INPUT_ERROR, NO_TESTS, and TESTS_LEFT.
Referenced by test_or_normal().
test_or_normal()
Status::Statuses test_or_normal (const char * filename)
Opens test file and decides: solver_proccess() or test_proccess()
Parameters
 in filename
Returns
Error::Errors
Definition at line 3 of file test.cpp.
                                                    {
    FILE* file = nullptr;
    switch (test_open_file(&file, filename)) {
        case TestMode::INPUT_ERROR:
            return Status::TEST_INPUT;
        case TestMode::TESTS_LEFT: // TEST mode
            return test_proccess(file);
        case TestMode::NO_TESTS: // Normal mode
            return solver_proccess();
        default:
            assert(0 && "test_open_file() returned wrong TestMode");
            break;
    }
    return Status::NO_ERROR;
}
References INPUT_ERROR, Status::NO_ERROR, NO_TESTS, solver_proccess(), Status::TEST_INPUT, test_open_file(), test_proccess(), and TESTS_LEFT.
Referenced by main().
test_print_summary()
void test_print_summary (const int test_num, const int passed_test_num)
Prints summary about all tests.
Parameters
 in test_num
 in passed_test_num
Definition at line 174 of file test.cpp.
                                                                      {
    if (test_num == passed_test_num) {
        if (test_num == 1)
            printf(CONSOLE_GREEN("Test passed.") " Congrats!\n");
        else
            printf(CONSOLE_GREEN("All %d tests passed.") " Congrats!\n", test_num);
    } else {
        if (test_num == 1)
            printf(CONSOLE_RED("WARNING! ") "Test failed\n");
        else {
            double success_percent = (double)passed_test_num * 100 / (double)test_num;
            printf(CONSOLE_RED("WARNING! ") "Passed %d of %d tests. It's %.1f%%\n",
                passed_test_num, test_num, success_percent);
        }
    }
}
References CONSOLE_GREEN, and CONSOLE_RED.
Referenced by test_proccess().
test_proccess()
Status::Statuses test_proccess (FILE * file)
Main test proccess (read, test)
Parameters
 in file
Returns
Error::Errors
Definition at line 19 of file test.cpp.
                                         {
    assert(file);
    TestMode tests = TestMode::INPUT_ERROR;
    int test_num = 0;
    int passed_test_num = 0;
    EqSolverData data = {};
    EqSolverData_init(&data);
    while ((tests = test_enter_coeffs(&data, file)) != TestMode::NO_TESTS) {
        if (tests == TestMode::INPUT_ERROR)
            return Status::TEST_INPUT;
        for (int i = 0; i < EqSolverData::COEFF_NUM; i++)
            assert(isfinite(data.coeffs[i]));
        solve_quad(&data);
        test_num++;
        switch (test_read_and_compare(&data, file, test_num)) {
            case TestResult::ERROR:
                return Status::TEST_INPUT;
            case TestResult::FAILED:
                break;
            case TestResult::PASSED:
                passed_test_num++;
                break;
            default:
                assert(0 && "test_check() returned incorrect TestResult");
                break;
        }
        EqSolverData_init(&data);
    }
    test_print_summary(test_num, passed_test_num);
    return Status::NO_ERROR;
}
References EqSolverData::COEFF_NUM, EqSolverData::coeffs, EqSolverData_init(), ERROR, FAILED, INPUT_ERROR, Status::NO_ERROR, NO_TESTS, PASSED, solve_quad(), test_enter_coeffs(), Status::TEST_INPUT, test_print_summary(), and test_read_and_compare().
Referenced by test_or_normal().
test_read_and_compare()
TestResult test_read_and_compare (const EqSolverData * data, FILE * file, const int test_n)
calls test_read_roots and test_compare_data
Parameters
 in data
 in file
 in test_n number of test
Returns
int success
Definition at line 160 of file test.cpp.
                                                                                         {
    assert(data);
    assert(file);
    EqSolverData correct_data = {};
    for (int i = 0; i < EqSolverData::COEFF_NUM - 1; i++)
        correct_data.roots[i] = NAN;
    if (!test_read_roots(data, &correct_data, file))
        return TestResult::ERROR;
    return test_compare_data(data, &correct_data, test_n);
}
References EqSolverData::COEFF_NUM, ERROR, EqSolverData::roots, test_compare_data(), and test_read_roots().
Referenced by test_proccess().
test_read_roots()
bool test_read_roots (const EqSolverData * data, EqSolverData * correct_data, FILE * file)
Reads correct roots from test file.
Parameters
 in data
 in correct_data
 in file
Returns
bool success
Definition at line 102 of file test.cpp.
                                                                                       {
    assert(data);
    assert(correct_data);
    assert(file);
    if (read_num(((int*)&correct_data->roots_num), file) != InputStatus::OK) {
        printf("Error reading number of solutions from test file\n");
        fclose(file);
        return false;
    }
    for (int i = 0; i < (int)correct_data->roots_num; i++) {
        if(read_num(&correct_data->roots[i], file, false) != InputStatus::OK) {
            printf("Error reading solution from test file\n");
            fclose(file);
            return false;
        }
    }
    if (!input_flush(file)) {
        printf("Error reading solution from test file\n");
        return false;
    }
    bubble_sort(correct_data->roots, correct_data->roots_num);
    return true;
}
References bubble_sort(), input_flush(), OK, read_num(), EqSolverData::roots, and EqSolverData::roots_num.
Referenced by test_read_and_compare().